----CRIACAO DO BANCO DB_AULA
--CREATE DATABASE MeuBanco

----CRIAÇÃO DO BANCO DBTESTE
--CREATE DATABASE dbteste
----EXCLUSÃO DO BANCO DBTESTE 
--DROP DATABASE dbteste

----SELECIONAR O BANCO DE DADOS QUE VOCE VAI TRABALHAR
USE MeuBanco

CREATE TABLE ALUNO(
    ID INT PRIMARY KEY,
    NOME NVARCHAR(150) NOT NULL,
    DATA_CADASTRO DATETIME DEFAULT GETDATE(),
    OBS VARCHAR(500)
)

--DROP TABLE ALUNO


ALTER TABLE ALUNO
ADD CPF VARCHAR(11)

ALTER TABLE ALUNO
DROP COLUMN OBS

CREATE TABLE TELEFONE(
    ID INT PRIMARY KEY, 
    TELEFONE VARCHAR(11),
    ID_ALUNO INT REFERENCES ALUNO(ID),
)

CREATE TABLE EMAIL(
    EMAIL VARCHAR(200), 
    ID_ALUNO INT REFERENCES ALUNO(ID),
    PRIMARY KEY (EMAIL, ID_ALUNO)
)